### PR TITLE
Edit and additions

### PR DESCRIPTION
**Pull request by stareagle**
I added my name to both supporters.txt file and made a small edit to the diversity statement document.

### CODE REVIEW

**Comment by escowles** [comment]
Sorry, @stareagle — another commit has caused a conflict.  Can you rebase?

**Comment by phette23** [comment]
Adds names to two supporters files—this can be merged.

Adds "political leaning" to diversity statement, this needs community discussion period per [our changes procedure](https://github.com/code4lib/code-of-conduct/blob/main/how_changes_are_made.md). So this needs to be 2 PRs. I can get to it eventually if no one else does.

**Comment by mjgiarlo** [comment]
@stareagle Are you still interested in shepherding this through, or not so much?

**Comment by mjgiarlo** [comment]
Note there are two conflicts that will need to be resolved, as well. Happy to help with this if you want to go forward with this PR.

**Comment by phette23** [comment]
So per [my earlier comment](https://github.com/code4lib/code-of-conduct/pull/63#issuecomment-739022691) this is sort of two PRs, but the only one we need to discuss is now redundant (political affiliation is already mentioned in the CoC). Therefore the last bit is adding @stareagle's name to the SUPPORTERS.txt which is fine and needs no discussion. If that's an incorrect interpretation, let me know — otherwise I'll merge this in a week

**Pull request closed without merging**
